version: 2.1

jobs:
  grade:
    docker:
      - image: continuumio/miniconda3:4.5.11

    working_directory: /tmp/repo
    steps:
      - checkout
      - run:
          name: Install grading dependencies
          command: |
            source activate base
            pip install --progress-bar off ipython ipywidgets
            pip install --progress-bar off https://github.com/nteract/papermill/archive/89a43a1bade7d9ba71b47a8a18cfc4d0b82e902a.zip
            pip install --progress-bar off https://github.com/earthlab/abc-classroom/archive/master.zip

      - run:
          name: Install course specific dependencies
          command: |
            source activate base
            [ -e environment.yml ] && conda env update --quiet -f environment.yml && conda clean -tipsy || echo nothing to do

      - run:
          name: "Prepare directories"
          command: |
            {% for nb_dir in notebook_dirs -%}
            mkdir -p notebooks/{{ nb_dir }}
            {% endfor %}
      {% for notebook in notebooks -%}
      - run:
          name: Execute {{ notebook }}.ipynb
          command: |
            source activate base
            papermill --cwd {{ notebook_dirs[loop.index0] }} {{ notebook }}.ipynb {{ notebook_names[loop.index0] }}-graded.ipynb
            jupyter nbconvert --to html --stdout {{ notebook }}-graded.ipynb > notebooks/{{ notebook }}.html
      {% endfor %}
      - store_artifacts:
          path: /tmp/repo/notebooks
          destination: notebooks

workflows:
  version: 2
  grade_me:
    jobs:
      - grade
