name: Codecov
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
jobs:
  run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    env:
      OS: ${{ matrix.os }}
      PYTHON: '3.10.5'
    steps:
    - uses: actions/checkout@master
    - name: Setup Python
      uses: actions/setup-python@master
      with:
        python-version: 3.10.5
    - name: setup git config
      run: |
        # Setup the git username and email, needed to run tests in test_github
        # only local git actions, so have no impact beyong tests.
        git config --global user.name "GitHub Actions Bot"
        git config --global user.email "abc.actions.bot@dummy.org"
    - name: Generate coverage report
      run: |
        pip install pytest
        pip install pytest-cov
        pip install -e .
        pytest --cov=./ --cov-report=xml
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1.0.5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.xml
        files: ./coverage1.xml,./coverage2.xml
        directory: ./coverage/reports/
        flags: unittests
        env_vars: OS,PYTHON
        name: codecov-umbrella
        fail_ci_if_error: true
        path_to_write_report: ./coverage/codecov_report.txt
        verbose: true
