# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Matrix OS / Python Version - Run Tests & Build Docs

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
jobs:
  setup-build:
    name: Ex1 (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        python-version: [3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r dev-requirements.txt
        pip install -e .
    - name: setup git config
      run: |
        # Setup the git username and email, needed to run tests in test_github
        # only local git actions, so have no impact beyong tests.
        git config --global user.name "GitHub Actions Bot"
        git config --global user.email "abc.actions.bot@dummy.org"

    - name: Test with pytest
      run: |
        pytest
    - name: Build Docs
      # Only run docs on python 3.8
      run: |
        make docs -B
    - name: Lint
      run: |
        black --check --verbose .
